# Generated by Django 3.1.6 on 2021-03-04 22:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackedstock',
            name='Quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='trackedstock',
            unique_together={('Symbol', 'Account')},
        ),
    ]
