# Generated by Django 3.1.6 on 2021-03-05 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_limitorders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='limitorders',
            name='Buy',
        ),
        migrations.AddField(
            model_name='limitorders',
            name='Type',
            field=models.CharField(default=None, max_length=3),
        ),
    ]
