# Generated by Django 3.1.6 on 2021-03-05 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20210305_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='limitorders',
            name='Quantity',
            field=models.IntegerField(default=0),
        ),
    ]
