# Generated by Django 3.1.6 on 2021-03-05 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_limitorders_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='limitorders',
            name='Stop',
            field=models.FloatField(default=0),
        ),
    ]
