# Generated by Django 3.1.6 on 2021-03-10 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20210306_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investor',
            name='money',
            field=models.FloatField(default=0),
        ),
    ]
