# Generated by Django 3.1.6 on 2021-03-12 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20210310_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='limitorders',
            name='OrginalPrice',
            field=models.FloatField(default=0),
        ),
    ]
