# Generated by Django 3.1.6 on 2021-03-28 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_fakeoptionchain_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='Type',
            field=models.CharField(default='', max_length=4),
        ),
        migrations.AddField(
            model_name='option',
            name='holder',
            field=models.BooleanField(default=True),
        ),
    ]
