# Generated by Django 3.1.6 on 2021-03-18 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='ticker',
            field=models.CharField(default='stock_ticker', max_length=20),
            preserve_default=False,
        ),
    ]
